version: 2

models:
  - name: dim_cities
    description: >
      List of cities of interest in Wake County including geocenter
  - name: dim_population
    description: >
      Population statistics for each city from 2010 through 2021
  - name: fact_parcels
    description: >
      Aggregated data table for all parcels and associated units for each combination of place, type_use, design_style, and land_class
      columns:
        - name: parcel_count
          description: The sum of the parcels for a given place
          tests:
            - not_null:
              severity: error
        - name: unit_count
          description: The sum of the units for a given place
          tests:
            - not_null:
              severity: error
  - name: fact_permits
    description: >
      Aggregated data table for all permits issued for a given place, status, permit_type, and proposed_use
    columns:
      - name: permit_count
        description: The sum of the permits for a given place
        tests:
          - not_null:
            severity: error
